version: "3.7"

services:
  app:
    build:
      context: ../yoda/php/8.1-xdebug
    image: somosyampi/php:8.1-xdebug
    init: true
    volumes:
    - .:/app:delegated
    networks:
      yampi:
      boilerplate:
        aliases:
        - server_bank

  nginx:
    build:
      context: ../yoda/http
    image: somosyampi/http
    volumes:
    - .:/app:delegated
    environment:
      FPM_HOST: server_bank
    networks:
      boilerplate:
      yampi:
        aliases:
        - server_bank.test
    depends_on:
    - app

networks:
  boilerplate:
    name: server_bank
  yampi:
    name: yampi
    external: true
